In [3]:
import pandas as pd

In [9]:
df1 = pd.read_csv("Airbnb_Open_Data.csv")

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_62282/1386405179.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("Airbnb_Open_Data.csv")

In [11]:
df1

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [15]:
df1.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [27]:
df1['id']

0         1001254
1         1002102
2         1002403
3         1002755
4         1003689
           ...
102594    6092437
102595    6092990
102596    6093542
102597    6094094
102598    6094647
Name: id, Length: 102599, dtype: int64

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
dtypes: float64(9), int64(2), object(14)
memory usage: 19.6+ MB

In [37]:
df1.drop(columns=['license'], inplace =True)

In [43]:
df1.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='object')

In [53]:
df1[df1['price'].isna()]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
147,1082524,Retreat in Williamsburg,22731046418,verified,Abraham,Brooklyn,Williamsburg,40.71492,-73.95935,United States,...,NaN,$64,4.0,240.0,6/17/2019,2.19,3.0,1.0,337.0,Leave shoes by door No strong scents (perfumes...
148,1083076,NYC Zen,83696952551,verified,Amelia,NaN,East Village,40.72354,-73.98295,United States,...,NaN,$119,3.0,30.0,6/17/2019,0.28,5.0,1.0,344.0,No Smoking No Pets No Parties
210,1117319,Private Garden Apt • New Renovation,760769897,NaN,Ryan,Brooklyn,Williamsburg,40.71625,-73.93845,United States,...,NaN,$176,2.0,253.0,7/2/2019,3.04,3.0,1.0,124.0,Just general respect for the place and my neig...
211,1117871,Modern comfort in art infused landmark Brownstone,25801284480,NaN,Tiana,Brooklyn,Bedford-Stuyvesant,40.68290,-73.93549,United States,...,NaN,$152,2.0,23.0,7/1/2019,0.22,5.0,1.0,137.0,"Enjoy your stay, and please take care of the a..."
212,1118424,"NOHO/EAST VILLAGE, PRIVATE 1/2 BATH",62325020363,NaN,Perkins,Manhattan,NoHo,40.72773,-73.99134,United States,...,NaN,$151,2.0,115.0,12/5/2018,1.17,2.0,1.0,192.0,SMOKING: Not allowed anywhere on the property!...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102046,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.69370,-73.91006,United States,...,NaN,NaN,5.0,3.0,4/9/2018,0.11,1.0,1.0,0.0,Please be mindful that I live in the same buil...
102047,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.71284,-73.96284,United States,...,NaN,NaN,7.0,15.0,1/1/2018,0.55,4.0,1.0,0.0,NaN
102048,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.79563,-73.97634,United States,...,NaN,NaN,3.0,38.0,6/10/2019,1.40,3.0,1.0,31.0,NaN
102049,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.76125,-73.98945,United States,...,NaN,NaN,1.0,81.0,3/5/2019,2.96,2.0,2.0,0.0,- I work at home and prefer to rent to folks w...
102050,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.68221,-73.94618,United States,...,NaN,NaN,2.0,104.0,6/12/2019,3.69,5.0,1.0,268.0,NaN

In [55]:
print(df1.isna()['price'].sum())

247

In [57]:
print(df1.isna()['availability 365'].sum())

448

In [61]:
df1.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='object')

In [105]:
Availability_check = df1.loc[df1["availability 365"].isna(), ["last review", "number of reviews", "calculated host listings count", "price", "host id", "NAME","lat","long"]]

In [107]:
Availability_check

,last review,number of reviews,calculated host listings count,price,host id,NAME,lat,long
50,6/17/2019,135.0,2.0,$212,49393946881,Fort Greene brownstone,40.69142,-73.97376
51,6/16/2019,112.0,3.0,$728,1529890895,Blue Room for 2 in Brownstone for $1350 monthly,40.68043,-73.93934
52,7/7/2019,73.0,1.0,$901,50562514538,Cozy 1BD on Central Park West in New York City,40.78635,-73.97008
53,5/17/2019,82.0,1.0,$335,49585766302,* ORIGINAL BROOKLYN LOFT *,40.70420,-73.93560
54,6/29/2019,328.0,1.0,$254,52857769781,Greenpoint Place...Has It All!,40.73506,-73.95392
...,...,...,...,...,...,...,...,...
87071,NaN,0.0,1.0,$448,24450034505,Doorman Chelsea One Bedroom- Convenient and Fun!,40.74179,-73.99855
87072,NaN,0.0,1.0,$639,47772968181,Beautiful Brownstone Triplex,40.68601,-73.98335
87073,7/19/2016,3.0,1.0,$894,36668499953,"Lovely, Sunny Studio near Central Park in UWS",40.79759,-73.96544
87099,NaN,0.0,1.0,"$1,096",27475689132,Master bedroom in penthouse apt of luxury buil...,40.75927,-73.98592
87100,NaN,0.0,1.0,$153,95943719493,Private Room on the East River!,40.78650,-73.94288

In [109]:
Availability_check.info()

<class 'pandas.core.frame.DataFrame'>
Index: 448 entries, 50 to 87100
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   last review                     180 non-null    object
 1   number of reviews               394 non-null    float64
 2   calculated host listings count  448 non-null    float64
 3   price                           448 non-null    object
 4   host id                         448 non-null    int64
 5   NAME                            430 non-null    object
 6   lat                             448 non-null    float64
 7   long                            448 non-null    float64
dtypes: float64(4), int64(1), object(3)
memory usage: 31.5+ KB

In [113]:
Availability_check[["last review", "number of reviews", "calculated host listings count", "price", "host id", "NAME","lat","long"]].isna().sum()

last review                       268
number of reviews                  54
calculated host listings count      0
price                               0
host id                             0
NAME                               18
lat                                 0
long                                0
dtype: int64

In [95]:
# now these are the values that are there when we are having availability 365 as NaN

In [97]:
# now i am seeing that if the there is no availability then how come there are prices, name, hostid, number of reviews, last review.

In [101]:
# i can also see if its has some lat and long. Yup they have lat and long.

In [115]:
for col in Availability_check.columns:
    print(f"\n{col}")
    print(Availability_check[col].value_counts()[Availability_check[col].value_counts() > 1])

last review
last review
3/2/2022      18
6/23/2019      8
11/15/2021     6
6/22/2019      6
6/24/2019      6
3/1/2022       5
6/30/2019      5
6/16/2019      4
6/27/2019      4
7/6/2019       4
6/20/2019      4
1/2/2019       3
7/2/2019       3
7/1/2019       3
5/31/2019      3
6/25/2019      3
6/28/2019      2
7/5/2019       2
5/21/2019      2
10/30/2016     2
7/19/2016      2
6/15/2019      2
5/26/2019      2
6/26/2019      2
6/21/2019      2
6/29/2019      2
6/18/2019      2
Name: count, dtype: int64

number of reviews
number of reviews
0.0      205
3.0       11
1.0        6
2.0        6
8.0        5
6.0        5
21.0       4
7.0        4
18.0       4
4.0        4
10.0       4
5.0        4
13.0       3
16.0       3
24.0       3
25.0       3
11.0       3
33.0       3
61.0       3
46.0       3
66.0       3
143.0      3
190.0      2
30.0       2
80.0       2
82.0       2
19.0       2
86.0       2
14.0       2
36.0       2
45.0       2
105.0      2
49.0       2
42.0       2
151.0      2
271.0      2
99.0       2
59.0       2
70.0       2
23.0       2
142.0      2
54.0       2
9.0        2
Name: count, dtype: int64

calculated host listings count
calculated host listings count
1.0      276
2.0       81
3.0       23
4.0       17
6.0       13
5.0       11
7.0        9
28.0       6
8.0        4
10.0       2
171.0      2
Name: count, dtype: int64

price
price
$1,065     4
$1,096     3
$1,056     3
$756       3
$804       3
          ..
$571       2
$596       2
$174       2
$137       2
$728       2
Name: count, Length: 66, dtype: int64

host id
Series([], Name: count, dtype: int64)

NAME
NAME
Comfort home                                          4
Clean One Bedroom                                     2
Shared living space in the Bronx!                     2
Gorgeous brand new Studio Apt 5 min from Manhattan    2
✿✿✿ COUNTRY COTTAGE IN THE CITY✿✿✿                    2
                                                     ..
Beverley Road - Close to subway Q and B.              2
Skyscraper Ultimate Luxury at the Heart of BKLYN.     2
Cute double room for the perfect Yankee fan           2
1A. Studio & Stay. 30 minutes to Midtown Manhattan    2
Modern room in luxury apartment                       2
Name: count, Length: 127, dtype: int64

lat
lat
40.66049    4
40.68780    4
40.69000    3
40.73776    3
40.66079    2
           ..
40.72626    2
40.80780    2
40.74754    2
40.66266    2
40.59173    2
Name: count, Length: 126, dtype: int64

long
long
-73.90959    4
-73.99865    3
-73.94314    3
-73.93788    3
-73.96162    2
            ..
-73.93837    2
-73.94194    2
-73.98908    2
-73.93521    2
-73.93508    2
Name: count, Length: 129, dtype: int64

In [117]:
cols = [
    "last review",
    "number of reviews",
    "calculated host listings count",
    "price",
    "host id",
    "NAME",
    "lat",
    "long"
]

(Availability_check[cols] == 0).sum()

last review                         0
number of reviews                 205
calculated host listings count      0
price                               0
host id                             0
NAME                                0
lat                                 0
long                                0
dtype: int64

In [157]:
condition = (
    Availability_check["last review"].isna()
    & (
        Availability_check["number of reviews"].isna()
        | (Availability_check["number of reviews"] == 0)
    )
)

In [163]:
condition_main = (
    df1["availability 365"].isna()
    & df1["last review"].isna()
    & (
        df1["number of reviews"].isna()
        | (df1["number of reviews"] == 0)
    )
)

In [167]:
Availability_check.drop(Availability_check[condition].index, inplace=True)

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_62282/1516330834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Availability_check.drop(Availability_check[condition].index, inplace=True)

In [151]:
df1.drop(df1[condition_main].index, inplace=True)

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_62282/1355092836.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1.drop(df1[condition_main].index, inplace=True)
/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_62282/1355092836.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1[condition_main].index, inplace=True)

In [169]:
Availability_check

,last review,number of reviews,calculated host listings count,price,host id,NAME,lat,long
50,6/17/2019,135.0,2.0,$212,49393946881,Fort Greene brownstone,40.69142,-73.97376
51,6/16/2019,112.0,3.0,$728,1529890895,Blue Room for 2 in Brownstone for $1350 monthly,40.68043,-73.93934
52,7/7/2019,73.0,1.0,$901,50562514538,Cozy 1BD on Central Park West in New York City,40.78635,-73.97008
53,5/17/2019,82.0,1.0,$335,49585766302,* ORIGINAL BROOKLYN LOFT *,40.70420,-73.93560
54,6/29/2019,328.0,1.0,$254,52857769781,Greenpoint Place...Has It All!,40.73506,-73.95392
...,...,...,...,...,...,...,...,...
62406,11/15/2021,6.0,1.0,$893,63831403145,Cozy 1 bedroom appt.,40.60080,-73.96185
62407,11/15/2021,3.0,186.0,$923,14525787015,138 Bowery-Furnished Apartment,40.72020,-73.99385
62408,11/15/2021,10.0,51.0,$531,50104939918,138 Bowery-Classic Queen Studio,40.72034,-73.99387
87060,10/30/2016,3.0,1.0,$204,41928669339,Large 1 bed apt in heart of Williamsburg,40.71911,-73.95828
87073,7/19/2016,3.0,1.0,$894,36668499953,"Lovely, Sunny Studio near Central Park in UWS",40.79759,-73.96544

In [171]:
condition.sum()

0

In [173]:
# now the values lef tin avalibality 365 are the ones that can be useful lets find that.